### ISSUE TITLE
apiServer ingress unreachable

### ISSUE THREAD

**Issue by savdbroek** [DependencyTrack/helm-charts#119]
Hi there,

I've been trying to setup Dependency Track with these helm charts but I can't seem to get the ingress correct. What I have now:

```
ingress:
  enabled: true
  hostname: "deptrack.example.com"
  annotations: {}
  #  nginx.ingress.kubernetes.io/rewrite-target: /
  tls:
    - secretName: deptrack.example.com
      hosts:
        - deptrack.example.com
```
        
So this works perfectly fine for the frontend, but I can't reach the apiServer on deptrack.example.com/api. I just get a 404. Upon enabling the currently commented annotation, I can reach the apiServer but not the frontend.

It's like deptrack.example.com/api points to podIP:8080/api. While deptrack.example.com/api should point to podIP:8080/

What am I doing wrong?
