### ISSUE TITLE
Allow for HPA configuration

### ISSUE THREAD

**Issue by zprebosnyak-lm** [DependencyTrack/helm-charts#184]
To allow the pods to utilize horizontal pod auto scaling the `replicas` and `strategy.type` fields of the deployment manifests need to be optionally turned on/off. 

Propose modifying the deployment templates like so:

```YAML
  {{- if .Values.notificationPublisher.replicas.enabled }}
  replicas: {{ .Values.notificationPublisher.replicas.replicaCount }}
  {{- end }}
  {{- if .Values.notificationPublisher.deployment.strategy.enabled }}
  strategy:
    type: {{ .Values.notificationPublisher.deployment.strategy.type }}
  {{- end }}
```

values.yaml
```YAML
  replicas:
    enabled: true
    replicaCount: 1
  deployment:
    # -- The deployment strategy to use.
    strategy:
      enabled: true
      type: RollingUpdate
```
