### ISSUE TITLE
ingress is missing "path: /mirror"

### ISSUE THREAD

**Issue by nitschSB** [DependencyTrack/helm-charts#232]
Hi,

I have noticed that the Ingress does not contain a path for `/mirror`. Therefore, these calls are routed to the frontend, which reports a 404. I was able to fix this via `postRenderers`:
```
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Ingress
              # name: dependency-track # depends on release-name
            patch: |
              - op: add
                path: /spec/rules/0/http/paths/-
                value:
                  backend:
                    service:
                      name: dependency-track-api-server # depends on release-name
                      port:
                        name: web
                  path: /mirror
                  pathType: Prefix
```
Perhaps you would like to add it to the chart?
