### ISSUE TITLE
Add startupProbe for API server to improve stability during initialization

### ISSUE THREAD

**Issue by renegrob** [DependencyTrack/helm-charts#239]
When deploying Dependency-Track using the Helm chart, the API server container may fail with CrashLoopBackOff errors if it doesn’t become ready before the livenessProbe or readinessProbe kicks in. This often happens when:

* OIDC is enabled (causing additional startup delay)
* External DBs are used
* Migrations are running at startup

The `/health/ready` endpoint isn't ready quickly enough, and the probes fail before the app is initialized. (In our case the initialization seems to take at least 2 minutes.)

**Add support for an optional startupProbe to the API server deployment, mirroring the existing readinessProbe.**

**Suggested values block:**
```yaml
apiServer:
  probes:
    startup:
      enabled: true
      failureThreshold: 30
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
```

**Suggested template addition (in `deployment.yaml` and `statfulset.yaml`):**
```yaml
{{- if .Values.apiServer.probes.startup.enabled }}
startupProbe:
  httpGet:
    scheme: HTTP
    port: web
    path: /health/ready
  failureThreshold: {{ .Values.apiServer.probes.startup.failureThreshold }}
  initialDelaySeconds: {{ .Values.apiServer.probes.startup.initialDelaySeconds }}
  periodSeconds: {{ .Values.apiServer.probes.startup.periodSeconds }}
  successThreshold: {{ .Values.apiServer.probes.startup.successThreshold }}
  timeoutSeconds: {{ .Values.apiServer.probes.startup.timeoutSeconds }}
{{- end }}
```

Tuning the `readinessProbe.initialDelaySeconds` is a workaround, but unreliable and hard to get right in dynamic environments. A startupProbe is the recommended Kubernetes-native solution for this problem.
