### ISSUE TITLE
unable to use openid

### ISSUE THREAD

**Issue by bjtox** [DependencyTrack/helm-charts#244]
i'm trying to setup OpenID configuration on my helm chart.

i've set up this vars

  frontend:
    extraEnv:
      - name: OIDC_CLIENT_ID
        value: "value"
      - name: OIDC_ISSUER
        value: "address"
      - name: OIDC_LOGIN_BUTTON_TEXT
        value: "Sign in with Platform"
    apiServer:
        extraEnv:
          - name: ALPINE_OIDC_ENABLED
            value: "true"
          - name: ALPINE_OIDC_CLIENT_ID
            value: "value"
          - name: ALPINE_OIDC_ISSUER
            value: "address"
          - name: ALPINE_OIDC_USERNAME_CLAIM
            value: preferred_username
          - name: ALPINE_OIDC_TEAMS_CLAIM
            value: groups
          - name: ALPINE_OIDC_USER_PROVISIONING
            value: "true"
          - name: ALPINE_OIDC_TEAM_SYNCHRONIZATION
            value: "true"

i've replate issuer and client_id with a placeholder for this ticket

but i don't see the openid button on login

![Image](https://github.com/user-attachments/assets/d697c5f7-d59a-402b-83a9-941622a0aadb)

could someone help me with this config? PS is a configuration using keycloak.

**Comment by bjtox** [comment]
ad info: no error logs appear in pod or in browser

**Comment by danihengeveld** [comment]
These are the settings we use for OIDC with Entra ID (irrelevant db config stripped) on the latest chart version and they work perfectly.
```yaml
apiServer:
  extraEnv:
    - name: ALPINE_CORS_ALLOW_ORIGIN
      value: "https://dtrack.example.com"
    - name: ALPINE_OIDC_ENABLED
      value: "true"
    - name: ALPINE_OIDC_CLIENT_ID
      value: "***"
    - name: ALPINE_OIDC_ISSUER
      value: "***"
    - name: ALPINE_OIDC_USERNAME_CLAIM
      value: preferred_username
    - name: ALPINE_OIDC_USER_PROVISIONING
      value: "true"
    - name: ALPINE_OIDC_TEAMS_CLAIM
      value: "groups"
    - name: ALPINE_OIDC_TEAM_SYNCHRONIZATION
      value: "true"
frontend:
  apiBaseUrl: "https://dtrack.example.com"
  extraEnv:
    - name: OIDC_CLIENT_ID
      value: "***"
    - name: OIDC_ISSUER
      value: "***"
    - name: OIDC_SCOPE
      value: "openid profile email GroupMember.Read.All"
ingress:
  enabled: false
```
